# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'medicalSYM_function_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Function(object):
    def setupUi(self, Function):
        Function.setObjectName("Function")
        Function.resize(1641, 1500)
        Function.setMinimumSize(QtCore.QSize(0, 1500))
        Function.setMaximumSize(QtCore.QSize(2000, 1500))
        Function.setStyleSheet("\n"
"\n"
"#widget{\n"
"    \n"
"    background-color:white;\n"
"\n"
"}\n"
"\n"
"")
        self.widget = QtWidgets.QWidget(Function)
        self.widget.setGeometry(QtCore.QRect(330, 60, 1291, 861))
        self.widget.setMinimumSize(QtCore.QSize(1291, 861))
        self.widget.setMaximumSize(QtCore.QSize(1291, 861))
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1291, 121))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setStyleSheet("#frame{\n"
"    border-bottom:1px solid  ;\n"
"    border-bottom-color: rgb(211, 211, 211);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.toolButton_5 = QtWidgets.QToolButton(self.frame)
        self.toolButton_5.setGeometry(QtCore.QRect(11, 69, 23, 23))
        self.toolButton_5.setText("")
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_7 = QtWidgets.QToolButton(self.frame)
        self.toolButton_7.setGeometry(QtCore.QRect(1220, 40, 51, 61))
        self.toolButton_7.setStyleSheet("border:none;")
        self.toolButton_7.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/function/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon)
        self.toolButton_7.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_7.setObjectName("toolButton_7")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(280, 60, 281, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("#lineEdit{\n"
"    \n"
"    background-color: rgba(0,0,0,0);\n"
"    font-size:21px;\n"
"    border:none;\n"
"    color:#717072;\n"
"    border-bottom:1px solid  rgba(60, 170, 255);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.toolButton_6 = QtWidgets.QToolButton(self.frame)
        self.toolButton_6.setGeometry(QtCore.QRect(0, -10, 241, 141))
        self.toolButton_6.setStyleSheet("image: url(:/background/logo.png);\n"
"border:none;")
        self.toolButton_6.setText("")
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_8 = QtWidgets.QToolButton(self.frame)
        self.toolButton_8.setGeometry(QtCore.QRect(540, 60, 20, 20))
        self.toolButton_8.setStyleSheet("border:none;\n"
"")
        self.toolButton_8.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/function/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon1)
        self.toolButton_8.setObjectName("toolButton_8")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(990, 60, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(60, 170, 255);\n"
"border:none;\n"
"font-size:21px;\n"
"background:transparent;")
        self.label_2.setObjectName("label_2")
        self.toolButton_11 = QtWidgets.QToolButton(self.frame)
        self.toolButton_11.setGeometry(QtCore.QRect(1070, 10, 101, 31))
        self.toolButton_11.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:15;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/function/switch_user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_11.setIcon(icon2)
        self.toolButton_11.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_11.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_11.setObjectName("toolButton_11")
        self.toolButton_12 = QtWidgets.QToolButton(self.frame)
        self.toolButton_12.setGeometry(QtCore.QRect(1180, 10, 101, 31))
        self.toolButton_12.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:15;\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/function/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_12.setIcon(icon3)
        self.toolButton_12.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_12.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_12.setObjectName("toolButton_12")
        self.toolButton_24 = QtWidgets.QToolButton(self.frame)
        self.toolButton_24.setGeometry(QtCore.QRect(250, 60, 31, 21))
        self.toolButton_24.setStyleSheet("background:transparent;\n"
"border:none;")
        self.toolButton_24.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/background/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_24.setIcon(icon4)
        self.toolButton_24.setObjectName("toolButton_24")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setGeometry(QtCore.QRect(0, 120, 221, 741))
        self.frame_2.setStyleSheet("#frame_2{\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"}\n"
"*{\n"
"    background:transparent;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_2.setGeometry(QtCore.QRect(0, 90, 231, 51))
        self.toolButton_2.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:23px;\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/function_menu/menu_0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon5)
        self.toolButton_2.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_3.setGeometry(QtCore.QRect(0, 140, 231, 51))
        self.toolButton_3.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:23px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/function_menu/menu_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon6)
        self.toolButton_3.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_4.setGeometry(QtCore.QRect(0, 190, 271, 51))
        self.toolButton_4.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:23px;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/function_menu/menu_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon7)
        self.toolButton_4.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_9 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_9.setGeometry(QtCore.QRect(0, 240, 271, 51))
        self.toolButton_9.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:23px;")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/function_menu/add_data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_9.setIcon(icon8)
        self.toolButton_9.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_9.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_9.setObjectName("toolButton_9")
        self.toolButton = QtWidgets.QToolButton(self.frame_2)
        self.toolButton.setGeometry(QtCore.QRect(0, 30, 221, 51))
        self.toolButton.setStyleSheet("border:none;\n"
"color: rgb(89, 153, 255);\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:27px;\n"
"")
        self.toolButton.setObjectName("toolButton")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(220, 120, 1071, 741))
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setStyleSheet("#stackedWidget{\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setStyleSheet("")
        self.page_0.setObjectName("page_0")
        self.frame_3 = QtWidgets.QFrame(self.page_0)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1071, 741))
        self.frame_3.setStyleSheet("#frame_3{\n"
"\n"
"    \n"
"    background-color: rgba(60, 170, 255,0.3);\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(12, 280, 864, 96))
        self.label.setStyleSheet("border:none;\n"
"font: 9pt \"华文彩云\";\n"
"color: white;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:40px;\n"
"background:transparent;\n"
"")
        self.label.setObjectName("label")
        self.wdt_player = QtWidgets.QWidget(self.frame_3)
        self.wdt_player.setGeometry(QtCore.QRect(-20, 10, 1211, 711))
        self.wdt_player.setStyleSheet("background-color: rgba(255, 255, 255,0.3);\n"
"font: 12pt \"楷体\";\n"
"font-size:32px;\n"
"border:none;\n"
"image: url(:/background/function_1.png);")
        self.wdt_player.setObjectName("wdt_player")
        self.wdt_player.raise_()
        self.label.raise_()
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.frame_5 = QtWidgets.QFrame(self.page_1)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1071, 741))
        self.frame_5.setStyleSheet("#frame_5{\n"
"\n"
"    \n"
"    background-color: rgba(60, 170, 255,0.3);\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(50, 30, 571, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame_5)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(60, 90, 971, 581))
        self.plainTextEdit_2.setStyleSheet("background-color: rgba(255, 255, 255,0.3);\n"
"font: 12pt \"楷体\";\n"
"font-size:32px;\n"
"border:none;")
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(70, 90, 811, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_31 = QtWidgets.QLabel(self.frame_5)
        self.label_31.setGeometry(QtCore.QRect(70, 370, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.frame_5)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(70, 150, 951, 201))
        self.plainTextEdit_3.setStyleSheet("background-color:transparent;\n"
"font: 12pt \"楷体\";\n"
"font-size:20px;\n"
"border:none;")
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.frame_5)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(90, 430, 921, 211))
        self.plainTextEdit_4.setStyleSheet("background-color:transparent;\n"
"font: 12pt \"楷体\";\n"
"font-size:20px;\n"
"border:none;")
        self.plainTextEdit_4.setReadOnly(True)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("")
        self.page_2.setObjectName("page_2")
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1131, 781))
        self.frame_4.setStyleSheet("#frame_4{\n"
"\n"
"    \n"
"    background-color: rgba(60, 170, 255,0.3);\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(50, 30, 571, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget.setGeometry(QtCore.QRect(80, 110, 951, 531))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("#tableWidget{\n"
"\n"
"    background-color: rgba(255, 255, 255,0.3);\n"
"}\n"
"*{\n"
"    font: 12pt \"楷体\";\n"
"}")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.toolButton_20 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_20.setGeometry(QtCore.QRect(540, 50, 101, 31))
        self.toolButton_20.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:15;")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/function/delete_data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_20.setIcon(icon9)
        self.toolButton_20.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_20.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_20.setObjectName("toolButton_20")
        self.stackedWidget.addWidget(self.page_2)
        self.page_department = QtWidgets.QWidget()
        self.page_department.setObjectName("page_department")
        self.frame_8 = QtWidgets.QFrame(self.page_department)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 1131, 781))
        self.frame_8.setStyleSheet("#frame_8{\n"
"\n"
"    \n"
"    background-color: rgba(60, 170, 255,0.3);\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setGeometry(QtCore.QRect(40, 50, 1021, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_8)
        self.plainTextEdit.setGeometry(QtCore.QRect(120, 140, 831, 531))
        self.plainTextEdit.setStyleSheet("background-color: rgba(255, 255, 255,0.3);\n"
"font: 12pt \"楷体\";\n"
"font-size:32px;\n"
"border:none;")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.toolButton_13 = QtWidgets.QToolButton(self.frame_8)
        self.toolButton_13.setGeometry(QtCore.QRect(20, 10, 101, 31))
        self.toolButton_13.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:15;\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/function/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_13.setIcon(icon10)
        self.toolButton_13.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_13.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_13.setObjectName("toolButton_13")
        self.stackedWidget.addWidget(self.page_department)
        self.page_consist = QtWidgets.QWidget()
        self.page_consist.setObjectName("page_consist")
        self.frame_9 = QtWidgets.QFrame(self.page_consist)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 1131, 781))
        self.frame_9.setStyleSheet("#frame_9{\n"
"\n"
"    \n"
"    background-color: rgba(60, 170, 255,0.3);\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        self.label_8.setGeometry(QtCore.QRect(40, 50, 1021, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.toolButton_14 = QtWidgets.QToolButton(self.frame_9)
        self.toolButton_14.setGeometry(QtCore.QRect(20, 10, 101, 31))
        self.toolButton_14.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:15;\n"
"")
        self.toolButton_14.setIcon(icon10)
        self.toolButton_14.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_14.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_14.setObjectName("toolButton_14")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_9)
        self.tableWidget_3.setGeometry(QtCore.QRect(80, 140, 941, 531))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_3.setStyleSheet("#tableWidget_3{\n"
"\n"
"    background-color: rgba(255, 255, 255,0.3);\n"
"}\n"
"*{\n"
"    font: 12pt \"楷体\";\n"
"}")
        self.tableWidget_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_3.setAutoScroll(False)
        self.tableWidget_3.setAlternatingRowColors(True)
        self.tableWidget_3.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_3.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_3.setShowGrid(True)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.horizontalHeader().setHighlightSections(True)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(True)
        self.toolButton_21 = QtWidgets.QToolButton(self.frame_9)
        self.toolButton_21.setGeometry(QtCore.QRect(130, 10, 101, 31))
        self.toolButton_21.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:15;")
        self.toolButton_21.setIcon(icon9)
        self.toolButton_21.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_21.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_21.setObjectName("toolButton_21")
        self.stackedWidget.addWidget(self.page_consist)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_6 = QtWidgets.QFrame(self.page_3)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 1071, 741))
        self.frame_6.setStyleSheet("#frame_6{\n"
"\n"
"    \n"
"    background-color: rgba(60, 170, 255,0.3);\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(50, 30, 571, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_2.setGeometry(QtCore.QRect(80, 110, 931, 531))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("#tableWidget_2{\n"
"\n"
"    background-color: rgba(255, 255, 255,0.3);\n"
"}\n"
"*{\n"
"    font: 12pt \"楷体\";\n"
"}")
        self.tableWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_2.setAutoScroll(False)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(True)
        self.toolButton_23 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_23.setGeometry(QtCore.QRect(420, 50, 101, 31))
        self.toolButton_23.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:15;")
        self.toolButton_23.setIcon(icon9)
        self.toolButton_23.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_23.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_23.setObjectName("toolButton_23")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.frame_7 = QtWidgets.QFrame(self.page_4)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 1071, 741))
        self.frame_7.setStyleSheet("#frame_7{\n"
"\n"
"    \n"
"    background-color: rgba(60, 170, 255,0.3);\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setGeometry(QtCore.QRect(30, 40, 1011, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.toolButton_16 = QtWidgets.QToolButton(self.frame_7)
        self.toolButton_16.setGeometry(QtCore.QRect(60, 180, 301, 321))
        self.toolButton_16.setStyleSheet("#toolButton_16{\n"
"background:transparent;\n"
"font:30pt \"楷体\";\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/function/科室.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_16.setIcon(icon11)
        self.toolButton_16.setIconSize(QtCore.QSize(400, 400))
        self.toolButton_16.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_16.setObjectName("toolButton_16")
        self.toolButton_18 = QtWidgets.QToolButton(self.frame_7)
        self.toolButton_18.setGeometry(QtCore.QRect(740, 180, 251, 321))
        self.toolButton_18.setStyleSheet("background:transparent;\n"
"font:30pt \"楷体\";")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/function/病人.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_18.setIcon(icon12)
        self.toolButton_18.setIconSize(QtCore.QSize(400, 400))
        self.toolButton_18.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_18.setObjectName("toolButton_18")
        self.toolButton_17 = QtWidgets.QToolButton(self.frame_7)
        self.toolButton_17.setGeometry(QtCore.QRect(430, 200, 231, 311))
        self.toolButton_17.setStyleSheet("background:transparent;\n"
"font:30pt \"楷体\";")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/function/医生.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_17.setIcon(icon13)
        self.toolButton_17.setIconSize(QtCore.QSize(400, 400))
        self.toolButton_17.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_17.setObjectName("toolButton_17")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setGeometry(QtCore.QRect(40, 580, 1011, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_11 = QtWidgets.QFrame(self.page)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 1071, 741))
        self.frame_11.setStyleSheet("#frame_11{\n"
"\n"
"    \n"
"    background-color: rgba(60, 170, 255,0.3);\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_13 = QtWidgets.QLabel(self.frame_11)
        self.label_13.setGeometry(QtCore.QRect(30, 50, 921, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.toolButton_22 = QtWidgets.QToolButton(self.frame_11)
        self.toolButton_22.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.toolButton_22.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:15;\n"
"")
        self.toolButton_22.setIcon(icon10)
        self.toolButton_22.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_22.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_22.setObjectName("toolButton_22")
        self.frame_14 = QtWidgets.QFrame(self.frame_11)
        self.frame_14.setGeometry(QtCore.QRect(60, 140, 941, 531))
        self.frame_14.setStyleSheet("background-color: rgba(255, 255, 255,0.3);\n"
"border:none;\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.toolButton_19 = QtWidgets.QToolButton(self.frame_14)
        self.toolButton_19.setGeometry(QtCore.QRect(50, 120, 251, 241))
        self.toolButton_19.setStyleSheet("background:transparent;\n"
"font:30pt \"楷体\";")
        self.toolButton_19.setText("")
        self.toolButton_19.setIcon(icon11)
        self.toolButton_19.setIconSize(QtCore.QSize(400, 400))
        self.toolButton_19.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_19.setObjectName("toolButton_19")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_14)
        self.lineEdit_12.setGeometry(QtCore.QRect(350, 100, 531, 41))
        self.lineEdit_12.setStyleSheet("background-color:white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_16 = QtWidgets.QLabel(self.frame_14)
        self.label_16.setGeometry(QtCore.QRect(350, 50, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background:transparent;")
        self.label_16.setObjectName("label_16")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_14)
        self.lineEdit_13.setGeometry(QtCore.QRect(350, 220, 531, 41))
        self.lineEdit_13.setStyleSheet("background-color: white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_17 = QtWidgets.QLabel(self.frame_14)
        self.label_17.setGeometry(QtCore.QRect(350, 170, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background:transparent;")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_14)
        self.label_18.setGeometry(QtCore.QRect(350, 280, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background:transparent;")
        self.label_18.setObjectName("label_18")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_14)
        self.lineEdit_14.setGeometry(QtCore.QRect(350, 330, 531, 41))
        self.lineEdit_14.setStyleSheet("background-color: white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.lineEdit_14.setText("")
        self.lineEdit_14.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_5.setGeometry(QtCore.QRect(350, 420, 531, 71))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"font-family:Microsoft Sans Serif;\n"
"    font-size:24px;\n"
"border:none;\n"
"    background-color: rgb(34, 189, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"    \n"
"    background-color: rgb(24, 155, 255);\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.page)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.frame_12 = QtWidgets.QFrame(self.page_5)
        self.frame_12.setGeometry(QtCore.QRect(0, 0, 1071, 741))
        self.frame_12.setStyleSheet("#frame_12{\n"
"\n"
"    \n"
"    background-color: rgba(60, 170, 255,0.3);\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_14 = QtWidgets.QLabel(self.frame_12)
        self.label_14.setGeometry(QtCore.QRect(30, 50, 941, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.toolButton_26 = QtWidgets.QToolButton(self.frame_12)
        self.toolButton_26.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.toolButton_26.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:15;\n"
"")
        self.toolButton_26.setIcon(icon10)
        self.toolButton_26.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_26.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_26.setObjectName("toolButton_26")
        self.frame_15 = QtWidgets.QFrame(self.frame_12)
        self.frame_15.setGeometry(QtCore.QRect(60, 140, 941, 531))
        self.frame_15.setStyleSheet("background-color: rgba(255, 255, 255,0.3);\n"
"border:none;\n"
"")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_15.setGeometry(QtCore.QRect(350, 70, 361, 41))
        self.lineEdit_15.setStyleSheet("background-color:white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.lineEdit_15.setText("")
        self.lineEdit_15.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_19 = QtWidgets.QLabel(self.frame_15)
        self.label_19.setGeometry(QtCore.QRect(350, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background:transparent;")
        self.label_19.setObjectName("label_19")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_16.setGeometry(QtCore.QRect(350, 180, 121, 41))
        self.lineEdit_16.setStyleSheet("background-color: white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.lineEdit_16.setText("")
        self.lineEdit_16.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_20 = QtWidgets.QLabel(self.frame_15)
        self.label_20.setGeometry(QtCore.QRect(350, 130, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background:transparent;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_15)
        self.label_21.setGeometry(QtCore.QRect(350, 240, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background:transparent;")
        self.label_21.setObjectName("label_21")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_17.setGeometry(QtCore.QRect(350, 290, 531, 41))
        self.lineEdit_17.setStyleSheet("background-color: white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.lineEdit_17.setText("")
        self.lineEdit_17.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_6.setGeometry(QtCore.QRect(350, 420, 531, 71))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"font-family:Microsoft Sans Serif;\n"
"    font-size:24px;\n"
"border:none;\n"
"    background-color: rgb(34, 189, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"    \n"
"    background-color: rgb(24, 155, 255);\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.toolButton_25 = QtWidgets.QToolButton(self.frame_15)
        self.toolButton_25.setGeometry(QtCore.QRect(60, 110, 231, 251))
        self.toolButton_25.setStyleSheet("background:transparent;\n"
"font:30pt \"楷体\";")
        self.toolButton_25.setText("")
        self.toolButton_25.setIcon(icon13)
        self.toolButton_25.setIconSize(QtCore.QSize(400, 400))
        self.toolButton_25.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_25.setObjectName("toolButton_25")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_4.setGeometry(QtCore.QRect(460, 350, 161, 41))
        self.comboBox_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_4.setAccessibleName("")
        self.comboBox_4.setStyleSheet("background-color: white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.comboBox_4.setFrame(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_22 = QtWidgets.QLabel(self.frame_15)
        self.label_22.setGeometry(QtCore.QRect(510, 130, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background:transparent;")
        self.label_22.setObjectName("label_22")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_18.setGeometry(QtCore.QRect(510, 180, 201, 41))
        self.lineEdit_18.setStyleSheet("background-color: white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.lineEdit_18.setText("")
        self.lineEdit_18.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_23 = QtWidgets.QLabel(self.frame_15)
        self.label_23.setGeometry(QtCore.QRect(730, 130, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background:transparent;")
        self.label_23.setObjectName("label_23")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_15)
        self.radioButton_3.setGeometry(QtCore.QRect(730, 180, 115, 19))
        self.radioButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_3.setStyleSheet("color:#717072;\n"
"background:white;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_15)
        self.radioButton_4.setGeometry(QtCore.QRect(730, 210, 115, 19))
        self.radioButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_4.setStyleSheet("color:#717072;\n"
"background:white;")
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_24 = QtWidgets.QLabel(self.frame_15)
        self.label_24.setGeometry(QtCore.QRect(350, 350, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background:transparent;")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_15)
        self.label_25.setGeometry(QtCore.QRect(630, 350, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background:transparent;")
        self.label_25.setObjectName("label_25")
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_6.setGeometry(QtCore.QRect(690, 350, 161, 41))
        self.comboBox_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_6.setAccessibleName("")
        self.comboBox_6.setStyleSheet("background-color: white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.comboBox_6.setFrame(True)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.frame_13 = QtWidgets.QFrame(self.page_6)
        self.frame_13.setGeometry(QtCore.QRect(0, 0, 1071, 741))
        self.frame_13.setStyleSheet("#frame_13{\n"
"\n"
"    \n"
"    background-color: rgba(60, 170, 255,0.3);\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_15 = QtWidgets.QLabel(self.frame_13)
        self.label_15.setGeometry(QtCore.QRect(30, 50, 981, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.toolButton_30 = QtWidgets.QToolButton(self.frame_13)
        self.toolButton_30.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.toolButton_30.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:15;\n"
"")
        self.toolButton_30.setIcon(icon10)
        self.toolButton_30.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_30.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_30.setObjectName("toolButton_30")
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        self.frame_16.setGeometry(QtCore.QRect(60, 140, 941, 531))
        self.frame_16.setStyleSheet("background-color: rgba(255, 255, 255,0.3);\n"
"border:none;\n"
"")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_19.setGeometry(QtCore.QRect(350, 110, 361, 41))
        self.lineEdit_19.setStyleSheet("background-color:white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.lineEdit_19.setText("")
        self.lineEdit_19.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_26 = QtWidgets.QLabel(self.frame_16)
        self.label_26.setGeometry(QtCore.QRect(350, 60, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background:transparent;")
        self.label_26.setObjectName("label_26")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_20.setGeometry(QtCore.QRect(350, 230, 121, 41))
        self.lineEdit_20.setStyleSheet("background-color: white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.lineEdit_20.setText("")
        self.lineEdit_20.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_27 = QtWidgets.QLabel(self.frame_16)
        self.label_27.setGeometry(QtCore.QRect(350, 170, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background:transparent;")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_16)
        self.label_28.setGeometry(QtCore.QRect(350, 280, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background:transparent;")
        self.label_28.setObjectName("label_28")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_21.setGeometry(QtCore.QRect(350, 330, 531, 41))
        self.lineEdit_21.setStyleSheet("background-color: white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.lineEdit_21.setText("")
        self.lineEdit_21.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_7.setGeometry(QtCore.QRect(350, 420, 531, 71))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"font-family:Microsoft Sans Serif;\n"
"    font-size:24px;\n"
"border:none;\n"
"    background-color: rgb(34, 189, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"    \n"
"    background-color: rgb(24, 155, 255);\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_29 = QtWidgets.QLabel(self.frame_16)
        self.label_29.setGeometry(QtCore.QRect(510, 170, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background:transparent;")
        self.label_29.setObjectName("label_29")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_22.setGeometry(QtCore.QRect(510, 230, 201, 41))
        self.lineEdit_22.setStyleSheet("background-color: white;\n"
"border:none;\n"
"font: 12pt \"楷体\";")
        self.lineEdit_22.setText("")
        self.lineEdit_22.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_30 = QtWidgets.QLabel(self.frame_16)
        self.label_30.setGeometry(QtCore.QRect(730, 170, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background:transparent;")
        self.label_30.setObjectName("label_30")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_16)
        self.radioButton_5.setGeometry(QtCore.QRect(730, 220, 115, 19))
        self.radioButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_5.setStyleSheet("color:#717072;\n"
"background:white;")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_16)
        self.radioButton_6.setGeometry(QtCore.QRect(730, 250, 115, 19))
        self.radioButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_6.setStyleSheet("color:#717072;\n"
"background:white;")
        self.radioButton_6.setObjectName("radioButton_6")
        self.toolButton_28 = QtWidgets.QToolButton(self.frame_16)
        self.toolButton_28.setGeometry(QtCore.QRect(60, 120, 221, 241))
        self.toolButton_28.setStyleSheet("background:transparent;\n"
"font:30pt \"楷体\";")
        self.toolButton_28.setText("")
        self.toolButton_28.setIcon(icon12)
        self.toolButton_28.setIconSize(QtCore.QSize(400, 400))
        self.toolButton_28.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_28.setObjectName("toolButton_28")
        self.stackedWidget.addWidget(self.page_6)
        self.page_records = QtWidgets.QWidget()
        self.page_records.setObjectName("page_records")
        self.frame_10 = QtWidgets.QFrame(self.page_records)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 1131, 781))
        self.frame_10.setStyleSheet("#frame_10{\n"
"\n"
"    \n"
"    background-color: rgba(60, 170, 255,0.3);\n"
"border-top:1px solid  ;\n"
"    border-top-color: rgb(211, 211, 211);\n"
"\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        self.label_9.setGeometry(QtCore.QRect(50, 50, 1011, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.toolButton_15 = QtWidgets.QToolButton(self.frame_10)
        self.toolButton_15.setGeometry(QtCore.QRect(20, 10, 101, 31))
        self.toolButton_15.setStyleSheet("color:black;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"font-size:15;\n"
"")
        self.toolButton_15.setIcon(icon10)
        self.toolButton_15.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_15.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_15.setObjectName("toolButton_15")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.frame_10)
        self.tableWidget_4.setGeometry(QtCore.QRect(80, 140, 941, 531))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_4.setStyleSheet("#tableWidget_4{\n"
"\n"
"    background-color: rgba(255, 255, 255,0.3);\n"
"}\n"
"*{\n"
"    font: 12pt \"楷体\";\n"
"}")
        self.tableWidget_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_4.setAutoScroll(False)
        self.tableWidget_4.setAlternatingRowColors(True)
        self.tableWidget_4.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_4.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_4.setShowGrid(True)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.tableWidget_4.horizontalHeader().setVisible(False)
        self.tableWidget_4.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_4.horizontalHeader().setHighlightSections(True)
        self.tableWidget_4.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.tableWidget_4.verticalHeader().setCascadingSectionResizes(True)
        self.stackedWidget.addWidget(self.page_records)

        self.retranslateUi(Function)
        self.stackedWidget.setCurrentIndex(0)
        self.toolButton_9.clicked.connect(Function.press_selected)
        self.toolButton_4.clicked.connect(Function.press_selected)
        self.toolButton_3.clicked.connect(Function.press_selected)
        self.toolButton_2.clicked.connect(Function.press_selected)
        self.toolButton_2.clicked.connect(Function.press_Hospital)
        self.toolButton_3.clicked.connect(Function.press_Doctor)
        self.toolButton_4.clicked.connect(Function.press_Patient)
        self.toolButton_9.clicked.connect(Function.press_Drug)
        self.toolButton_6.clicked.connect(Function.press_Logo)
        self.toolButton_12.clicked.connect(Function.close)
        self.toolButton_13.clicked.connect(Function.press_Doctor)
        self.toolButton_14.clicked.connect(Function.press_Doctor)
        self.toolButton_15.clicked.connect(Function.press_Patient)
        self.toolButton_16.clicked.connect(Function.press_keshi)
        self.toolButton_17.clicked.connect(Function.press_yisheng)
        self.toolButton_18.clicked.connect(Function.press_huanzhe)
        self.toolButton_22.clicked.connect(Function.press_Drug)
        self.toolButton_26.clicked.connect(Function.press_Drug)
        self.toolButton_30.clicked.connect(Function.press_Drug)
        self.toolButton_19.clicked.connect(Function.get_txtfile)
        self.toolButton_25.clicked.connect(Function.get_pngfile)
        self.pushButton_5.clicked.connect(Function.dep_2data)
        self.pushButton_6.clicked.connect(Function.doc_2data)
        self.pushButton_7.clicked.connect(Function.pt_2data)
        self.toolButton_20.clicked.connect(Function.delete_dep)
        self.toolButton_21.clicked.connect(Function.delete_doc)
        self.toolButton_23.clicked.connect(Function.delete_pt)
        self.toolButton_24.clicked.connect(Function.search_data)
        self.toolButton_8.clicked.connect(Function.search_clear)
        self.toolButton_11.clicked.connect(Function.ID_switch)
        QtCore.QMetaObject.connectSlotsByName(Function)

    def retranslateUi(self, Function):
        _translate = QtCore.QCoreApplication.translate
        Function.setWindowTitle(_translate("Function", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Function", "Search..."))
        self.label_2.setText(_translate("Function", "Welcome, user :  BIT369"))
        self.toolButton_11.setText(_translate("Function", "IDswitch"))
        self.toolButton_12.setText(_translate("Function", "   Exit"))
        self.toolButton_2.setText(_translate("Function", "      Hospital"))
        self.toolButton_3.setText(_translate("Function", "      Doctor"))
        self.toolButton_4.setText(_translate("Function", "      Patient"))
        self.toolButton_9.setText(_translate("Function", "      DataADD"))
        self.toolButton.setText(_translate("Function", "MAIN MENU"))
        self.label.setText(_translate("Function", "                  WELCOME 2 MEDICAL_DATA_SYSTEM \n"
"                           MAKE U LIFE HEALTHIER^ ^"))
        self.label_6.setText(_translate("Function", "HOSPITAL"))
        self.label_12.setText(_translate("Function", "IntroductionOfUs"))
        self.label_31.setText(_translate("Function", "Search Result"))
        self.plainTextEdit_3.setPlainText(_translate("Function", "    坐落在成都快乐宫旁、浣花溪畔的四川省人民医院，建于1941年，前身四川省公立医院是中央大学医学院附属医院，1952年命名为四川省人民医院，1989年评为首批国家三级甲等医院， 2002年与四川省医学科学院（前身为中国医学科学院四川分院）合并，成为四川省医学科学院•四川省人民医院。2012年，由四川省人民政府与中国科学院合作共建的中国科学院四川转化医学研究医院挂牌。2013年，与电子科技大学合作共建电子科技大学医学院，成为电子科技大学附属医院。\n"
"    医院秉承“一院多区、协同发展；全面推进、重点突出；科教兴院、人才强院”发展理念，以院本部为主体，包括青羊院区（院本部、皮肤病性病研究所、省老年医学中心）、龙泉院区(东院)、温江院区（省精神医学中心、温江科研基地）、高新院区（实验动物研究所、高新科研基地）、成都铁路卫生学校，形成集临床医疗、保健医疗、教学科研为一体的发展格局，先后荣获全国文明单位、全国百佳医院、全国抗震救灾英雄集体、全国抗击新冠肺炎疫情先进集体、全国卫生系统先进集体、全国卫生文化先进单位等荣誉。2020年，在复旦版《中国医院排行榜》上位居第57名，连续4年保持上升态势，较2019年再升27名，创医院近年来最快攀升纪录，健康管理和临床药学均进入全国十强；在全国三级公立医院绩效考核中排名第27位，继续保持国家监测指标等级A+；在《中国医院科技量值(STEM)综合榜单》上，医院综合排名位居72位，眼科学、肾脏病学等18个专科榜上有名。\n"
"    医院现有开放病床4051张，职工7091人，高级职称1072人。获得省部级各类人才称号200余人次，其中，中国科学院院士1人，国字号人才17人，国家有突出贡献中青年专家4人、享受国务院特殊津贴专家44人，四川省学术技术带头人24人，四川省“天府峨眉计划”入选者25人，四川省“天府青城计划”入选者17人。省内首家取得互联网医院执业资质，通过电子病历系统应用功能五级评价，拥有世界一流的达芬奇机器人手术系统、天玑手术机器人、PET-CT、TrueBeam直线加速器等医疗设备，开展了器官移植、细胞移植、大血管、瓣膜置换修复（包括TAVI、MitraClip等）、心室辅助治疗等高新手术，拥有人类疾病分子生物学与基因检测技术、人胰岛细胞分离等一大批具有国际先进水平的尖端技术，开展小儿尿道下裂成形术、心房颤动左心耳封堵术等特色医疗，自主完成全国首例正式上市国产人工心脏植入手术，牵头搭建5G+急性卒中天网智慧医疗急救体系，肾脏病理、基因分子诊断、危重症血液净化治疗全国领先。获得国家卫健委所有实体器官移植准入资质，并且实际应用于临床开展。是国家卫健委“优质护理服务示范工程”重点联系医院，首批国家级临床护理重点专科及护士岗位管理试点医院。"))
        self.plainTextEdit_4.setPlaceholderText(_translate("Function", "Please Use The Search_Bar Above To Find The Relative Data U Want~"))
        self.label_3.setText(_translate("Function", "DEPARTMENTS_TABLE"))
        self.tableWidget.setSortingEnabled(False)
        self.toolButton_20.setText(_translate("Function", "  Delete"))
        self.label_7.setText(_translate("Function", "DEPARTMENT_INFO"))
        self.toolButton_13.setText(_translate("Function", " Return"))
        self.label_8.setText(_translate("Function", "DEPARTMENT_CONSIST"))
        self.toolButton_14.setText(_translate("Function", " Return"))
        self.tableWidget_3.setSortingEnabled(False)
        self.toolButton_21.setText(_translate("Function", "  Delete"))
        self.label_5.setText(_translate("Function", "PATIENTS_TABLE"))
        self.tableWidget_2.setSortingEnabled(False)
        self.toolButton_23.setText(_translate("Function", "  Delete"))
        self.label_10.setText(_translate("Function", "DATA_ADD_SELECT"))
        self.toolButton_16.setText(_translate("Function", "科室"))
        self.toolButton_18.setText(_translate("Function", "患者"))
        self.toolButton_17.setText(_translate("Function", "医生"))
        self.label_11.setText(_translate("Function", "CLICK WHICHEVER YOU WANT TO FIX THE DATA!"))
        self.label_13.setText(_translate("Function", "ADD_DATA_2_DEPARTMENTS"))
        self.toolButton_22.setText(_translate("Function", " Return"))
        self.lineEdit_12.setPlaceholderText(_translate("Function", "Please enter the new Department\'s name"))
        self.label_16.setText(_translate("Function", "科室名称"))
        self.lineEdit_13.setPlaceholderText(_translate("Function", "Please enter the new Department\'s location"))
        self.label_17.setText(_translate("Function", "科室位置"))
        self.label_18.setText(_translate("Function", "科室介绍文件"))
        self.lineEdit_14.setPlaceholderText(_translate("Function", "Click the left btn to choose the TxtFile"))
        self.pushButton_5.setText(_translate("Function", "Data Inbound"))
        self.label_14.setText(_translate("Function", "ADD_DATA_2_DOCTORS"))
        self.toolButton_26.setText(_translate("Function", " Return"))
        self.lineEdit_15.setPlaceholderText(_translate("Function", "Please enter the new Doctor\'s name"))
        self.label_19.setText(_translate("Function", "医生姓名"))
        self.lineEdit_16.setPlaceholderText(_translate("Function", "Age"))
        self.label_20.setText(_translate("Function", "医生年龄"))
        self.label_21.setText(_translate("Function", "医生介绍文件"))
        self.lineEdit_17.setPlaceholderText(_translate("Function", "Click the left btn to choose the PngFile"))
        self.pushButton_6.setText(_translate("Function", "Data Inbound"))
        self.comboBox_4.setItemText(0, _translate("Function", "儿科"))
        self.comboBox_4.setItemText(1, _translate("Function", "耳鼻喉头颈外科"))
        self.label_22.setText(_translate("Function", "医生联系方式"))
        self.lineEdit_18.setPlaceholderText(_translate("Function", "Telephone Number"))
        self.label_23.setText(_translate("Function", "医生性别"))
        self.radioButton_3.setText(_translate("Function", "Female"))
        self.radioButton_4.setText(_translate("Function", "Male"))
        self.label_24.setText(_translate("Function", "所属科室"))
        self.label_25.setText(_translate("Function", "等级"))
        self.comboBox_6.setItemText(0, _translate("Function", "1"))
        self.comboBox_6.setItemText(1, _translate("Function", "2"))
        self.comboBox_6.setItemText(2, _translate("Function", "3"))
        self.label_15.setText(_translate("Function", "ADD_DATA_2_PATIENTS"))
        self.toolButton_30.setText(_translate("Function", " Return"))
        self.lineEdit_19.setPlaceholderText(_translate("Function", "Please enter the new Doctor\'s name"))
        self.label_26.setText(_translate("Function", "患者姓名"))
        self.lineEdit_20.setPlaceholderText(_translate("Function", "Age"))
        self.label_27.setText(_translate("Function", "患者年龄"))
        self.label_28.setText(_translate("Function", "居住地址"))
        self.lineEdit_21.setPlaceholderText(_translate("Function", "Please enter the new Patient\'s LivingLocation"))
        self.pushButton_7.setText(_translate("Function", "Data Inbound"))
        self.label_29.setText(_translate("Function", "患者联系方式"))
        self.lineEdit_22.setPlaceholderText(_translate("Function", "Telephone Number"))
        self.label_30.setText(_translate("Function", "患者性别"))
        self.radioButton_5.setText(_translate("Function", "Female"))
        self.radioButton_6.setText(_translate("Function", "Male"))
        self.label_9.setText(_translate("Function", "PATIENTS_RECORD"))
        self.toolButton_15.setText(_translate("Function", " Return"))
        self.tableWidget_4.setSortingEnabled(False)
import login
