# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'medicalSYM_finallogin_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1582, 1104)
        Login.setMinimumSize(QtCore.QSize(1300, 1000))
        Login.setMaximumSize(QtCore.QSize(9999, 9999))
        Login.setStyleSheet("*{\n"
"    font-family:Microsoft Sans Serif;\n"
"    font-size:24px;\n"
"border:none;\n"
"}\n"
"\n"
"#widget{\n"
"    border-radius:15px;\n"
"    background-image: url(:/background/login_0.jpg);\n"
"}\n"
"\n"
"QFrame{\n"
"    background:rgba(0,0,0,0.8);\n"
"    border-radius:15px;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    background:red;\n"
"    border-radius:60px;\n"
"}\n"
"\n"
"QToolButton{\n"
"    background:red;\n"
"    border-radius:60px;\n"
"}\n"
"QPushButton{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"    background:#ff696b;\n"
"}\n"
"QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:#717072;\n"
"    border-bottom:1px solid #717072;\n"
"}\n"
"#pushButton_2{\n"
"    \n"
"    background-color: rgba(0,0,0,0);\n"
"    font-size:21px;\n"
"    border:none;\n"
"    color:#717072;\n"
"    border-bottom:1px solid #717072;\n"
"}\n"
"#pushButton_6{\n"
"    \n"
"    background-color: rgba(0,0,0,0);\n"
"    font-size:21px;\n"
"    border:none;\n"
"    color:#717072;\n"
"    border-bottom:1px solid #717072;\n"
"}")
        self.frame = QtWidgets.QFrame(Login)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(470, 220, 501, 591))
        self.frame.setAccessibleName("")
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 80, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("*{\n"
"    color:white;\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(30, 480, 441, 71))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(40, 210, 431, 41))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 340, 431, 41))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("*{\n"
"    color:white;\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 290, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("*{\n"
"    color:white;\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 420, 201, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.toolButton = QtWidgets.QToolButton(Login)
        self.toolButton.setGeometry(QtCore.QRect(660, 160, 121, 121))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UIresource/icon_login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(35, 35))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(Login)
        self.toolButton_2.setGeometry(QtCore.QRect(1480, 110, 41, 31))
        self.toolButton_2.setStyleSheet("\n"
"QToolButton{\n"
"    background:transparent;\n"
"    image: url(:/background/icon_exit.png);\n"
"}\n"
"QToolButton:hover{\n"
"    background:transparent;\n"
"    image: url(:/background/icon_hover.png);\n"
"}")
        self.toolButton_2.setText("")
        self.toolButton_2.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_2.setObjectName("toolButton_2")
        self.widget = QtWidgets.QWidget(Login)
        self.widget.setGeometry(QtCore.QRect(380, 90, 1151, 841))
        self.widget.setObjectName("widget")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setEnabled(True)
        self.frame_2.setGeometry(QtCore.QRect(90, 130, 971, 591))
        self.frame_2.setAccessibleName("")
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(150, 70, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("*{\n"
"    color:white;\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(510, 480, 441, 71))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(40, 170, 431, 41))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(40, 270, 431, 41))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(40, 120, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("*{\n"
"    color:white;\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"}\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(40, 220, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("*{\n"
"    color:white;\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"}\n"
"")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(510, 20, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("*{\n"
"    color:white;\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"}\n"
"")
        self.label_16.setObjectName("label_16")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(510, 70, 431, 41))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(510, 120, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("*{\n"
"    color:white;\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"}\n"
"")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(40, 320, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("*{\n"
"    color:white;\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"}\n"
"")
        self.label_18.setObjectName("label_18")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(40, 370, 431, 41))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(40, 420, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("*{\n"
"    color:white;\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"}\n"
"")
        self.label_19.setObjectName("label_19")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(40, 470, 431, 41))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(510, 220, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("*{\n"
"    color:white;\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"}\n"
"")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(510, 320, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("*{\n"
"    color:white;\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"}\n"
"")
        self.label_21.setObjectName("label_21")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_3.setGeometry(QtCore.QRect(510, 190, 115, 19))
        self.radioButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_3.setStyleSheet("color:#717072;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_4.setGeometry(QtCore.QRect(630, 190, 115, 19))
        self.radioButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_4.setStyleSheet("color:#717072;")
        self.radioButton_4.setObjectName("radioButton_4")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame_2)
        self.dateEdit_2.setGeometry(QtCore.QRect(510, 270, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(-1)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dateEdit_2.setStyleSheet("color: rgb(113, 112, 114);\n"
"background:transparent;\n"
"border:none;")
        self.dateEdit_2.setProperty("showGroupSeparator", False)
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2002, 2, 2), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateEdit_2.setCalendarPopup(False)
        self.dateEdit_2.setCurrentSectionIndex(0)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_2.setGeometry(QtCore.QRect(510, 370, 431, 61))
        self.comboBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_2.setAccessibleName("")
        self.comboBox_2.setStyleSheet("color: rgb(113, 112, 114);\n"
"background:transparent;")
        self.comboBox_2.setFrame(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 30, 61, 28))
        self.pushButton_6.setStyleSheet("#pushButton_2{\n"
"    \n"
"    background-color: rgba(0,0,0,0);\n"
"    font-size:21px;\n"
"    border:none;\n"
"    color:#717072;\n"
"    border-bottom:1px solid #717072;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_3.setGeometry(QtCore.QRect(470, 390, 511, 111))
        self.toolButton_3.setStyleSheet("#toolButton_3{\n"
"border:none;\n"
"background:transparent;\n"
"color:white;\n"
"\n"
"}")
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_4.setGeometry(QtCore.QRect(520, 420, 431, 61))
        self.toolButton_4.setStyleSheet("#toolButton_4{\n"
"border:none;\n"
"background:transparent;\n"
"color:white;\n"
"\n"
"}")
        self.toolButton_4.setObjectName("toolButton_4")
        self.widget.raise_()
        self.toolButton_2.raise_()
        self.frame.raise_()
        self.toolButton.raise_()

        self.retranslateUi(Login)
        self.toolButton_2.clicked.connect(Login.close)
        self.pushButton_2.clicked.connect(Login.login2register)
        self.pushButton_6.clicked.connect(Login.register2login)
        self.pushButton_5.clicked.connect(Login.press_register)
        self.pushButton.clicked.connect(Login.press_login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.label.setText(_translate("Login", "                WELCOME TO MDS！\n"
"                       LOGIN HERE"))
        self.pushButton.setText(_translate("Login", "Login"))
        self.label_2.setText(_translate("Login", "Username"))
        self.label_3.setText(_translate("Login", "Password"))
        self.pushButton_2.setText(_translate("Login", "Register An Account "))
        self.label_13.setText(_translate("Login", "USER REGISTER"))
        self.pushButton_5.setText(_translate("Login", "Register"))
        self.lineEdit_8.setPlaceholderText(_translate("Login", "Please enter account number"))
        self.lineEdit_9.setPlaceholderText(_translate("Login", "Please enter your password"))
        self.label_14.setText(_translate("Login", "Username"))
        self.label_15.setText(_translate("Login", "Password"))
        self.label_16.setText(_translate("Login", "Name"))
        self.lineEdit_12.setPlaceholderText(_translate("Login", "Please enter your real name"))
        self.label_17.setText(_translate("Login", "Gender"))
        self.label_18.setText(_translate("Login", "Telephone"))
        self.lineEdit_10.setPlaceholderText(_translate("Login", "Please enter your phone number"))
        self.label_19.setText(_translate("Login", "Email"))
        self.lineEdit_11.setPlaceholderText(_translate("Login", "Please enter your email address"))
        self.label_20.setText(_translate("Login", "Date of birth"))
        self.label_21.setText(_translate("Login", "Position in the hospital"))
        self.radioButton_3.setText(_translate("Login", "Female"))
        self.radioButton_4.setText(_translate("Login", "Male"))
        self.dateEdit_2.setDisplayFormat(_translate("Login", "yyyy-M-d"))
        self.comboBox_2.setItemText(0, _translate("Login", "None"))
        self.comboBox_2.setItemText(1, _translate("Login", "Work-service personnel"))
        self.comboBox_2.setItemText(2, _translate("Login", "Professional staff"))
        self.comboBox_2.setItemText(3, _translate("Login", "Administrative staff"))
        self.pushButton_6.setText(_translate("Login", "BACK"))
        self.toolButton_3.setText(_translate("Login", "In the register..."))
        self.toolButton_4.setText(_translate("Login", "All information must be filled inT.T"))
import login
